from __future__ import annotations

from .models import ArtifactSpec, AuthoritySurface, HashClaim


def _spec(
    artifact_id: str,
    relative_path: str,
    surface_id: str,
    role: str,
    *,
    required: bool = True,
    authority_tier: int = 2,
    provenance_tracked: bool = False,
    description: str = "",
    notes: tuple[str, ...] = (),
) -> ArtifactSpec:
    return ArtifactSpec(
        artifact_id=artifact_id,
        relative_path=relative_path,
        surface_id=surface_id,
        role=role,
        required=required,
        authority_tier=authority_tier,
        provenance_tracked=provenance_tracked,
        description=description,
        notes=notes,
    )


def _claim(
    claim_label: str,
    artifact_id: str,
    published_sha256: str,
    claim_source: str,
    *,
    corroborators: tuple[str, ...] = (),
    required: bool = True,
    notes: tuple[str, ...] = (),
) -> HashClaim:
    return HashClaim(
        claim_label=claim_label,
        artifact_id=artifact_id,
        published_sha256=published_sha256,
        claim_source=claim_source,
        corroborators=corroborators,
        required=required,
        notes=notes,
    )


def _surface(
    surface_id: str,
    title: str,
    primary_artifact_ids: tuple[str, ...],
    *,
    corroborating_artifact_ids: tuple[str, ...] = (),
    notes: tuple[str, ...] = (),
) -> AuthoritySurface:
    return AuthoritySurface(
        surface_id=surface_id,
        title=title,
        primary_artifact_ids=primary_artifact_ids,
        corroborating_artifact_ids=corroborating_artifact_ids,
        notes=notes,
    )


ARTIFACT_SPECS: tuple[ArtifactSpec, ...] = (
    _spec(
        "i3_train",
        "data/v1_0/dataset_v1_0_stage_b_recovery_i3_train.jsonl",
        "i3",
        "primary",
        description="Frozen i3 control train JSONL",
    ),
    _spec(
        "i3_val",
        "data/v1_0/dataset_v1_0_stage_b_recovery_i3_val.jsonl",
        "i3",
        "primary",
        description="Frozen i3 control validation JSONL",
    ),
    _spec(
        "i3_summary",
        "data/v1_0/dataset_v1_0_stage_b_recovery_i3_summary.json",
        "i3",
        "corroborating",
        description="Published i3 summary JSON",
    ),
    _spec(
        "i3_config",
        "configs/lora/stage_b_llama31_8b_base_v1_i3.config.json",
        "i3",
        "corroborating",
        description="Frozen i3 config",
    ),
    _spec(
        "i3_manifest",
        "manifests/runs/stage_b_llama31_8b_base_v1_i3.run_manifest.json",
        "i3",
        "corroborating",
        description="Frozen i3 run manifest",
    ),
    _spec(
        "H0_config",
        "configs/lora/stage_b_llama31_8b_base_v1_phase_i_h0_control_i3_micro.config.json",
        "H0",
        "primary",
        description="Frozen H0 config",
    ),
    _spec(
        "H0_manifest",
        "manifests/runs/stage_b_llama31_8b_base_v1_phase_i_h0_control_i3_micro.run_manifest.json",
        "H0",
        "primary",
        description="Frozen H0 run manifest",
    ),
    _spec(
        "H0_eval_summary",
        "evals/runs/stage_b_v1_phase_i_h0_control_i3_micro_eval_20260611T103048Z/summary.json",
        "H0",
        "corroborating",
        description="Executed H0 eval summary",
    ),
    _spec(
        "H0_eval_rows",
        "evals/runs/stage_b_v1_phase_i_h0_control_i3_micro_eval_20260611T103048Z/comparison_rows.jsonl",
        "H0",
        "corroborating",
        description="Executed H0 eval comparison rows",
    ),
    _spec(
        "H1_train",
        "data/v1_0/dataset_v1_0_phase_i_h1_diversity_patch_train.jsonl",
        "H1",
        "primary",
        description="Frozen H1 train JSONL",
    ),
    _spec(
        "H1_val",
        "data/v1_0/dataset_v1_0_phase_i_h1_diversity_patch_val.jsonl",
        "H1",
        "primary",
        description="Frozen H1 validation JSONL",
    ),
    _spec(
        "H1_summary",
        "data/v1_0/dataset_v1_0_phase_i_h1_diversity_patch_summary.json",
        "H1",
        "corroborating",
        description="Published H1 summary JSON",
    ),
    _spec(
        "H1_config",
        "configs/lora/stage_b_llama31_8b_base_v1_phase_i_h1_diversity_patch.config.json",
        "H1",
        "primary",
        description="Frozen H1 config",
    ),
    _spec(
        "H1_manifest",
        "manifests/runs/stage_b_llama31_8b_base_v1_phase_i_h1_diversity_patch.run_manifest.json",
        "H1",
        "primary",
        description="Frozen H1 run manifest",
    ),
    _spec(
        "H1_eval_summary",
        "evals/runs/stage_b_v1_phase_i_h1_diversity_patch_eval_20260611T125835Z/summary.json",
        "H1",
        "corroborating",
        description="Executed H1 eval summary",
    ),
    _spec(
        "H1_eval_rows",
        "evals/runs/stage_b_v1_phase_i_h1_diversity_patch_eval_20260611T125835Z/comparison_rows.jsonl",
        "H1",
        "corroborating",
        description="Executed H1 eval comparison rows",
    ),
    _spec(
        "H1_bundle_manifest",
        "evals/baselines/llama31/internal_reference_regimes/h1_diversity_patch_20260611T125835Z/package_manifest.json",
        "H1",
        "corroborating",
        description="Published H1 bundle manifest",
    ),
    _spec(
        "H1_bundle_summary",
        "evals/baselines/llama31/internal_reference_regimes/h1_diversity_patch_20260611T125835Z/summary.json",
        "H1",
        "corroborating",
        description="Published H1 bundle summary",
    ),
    _spec(
        "H1_bundle_rows",
        "evals/baselines/llama31/internal_reference_regimes/h1_diversity_patch_20260611T125835Z/comparison_rows.jsonl",
        "H1",
        "corroborating",
        description="Published H1 bundle comparison rows",
    ),
    _spec(
        "H2_train",
        "data/v1_0/dataset_v1_0_phase_i_h2_commitment_patch_train.jsonl",
        "H2",
        "primary",
        description="Frozen H2 train JSONL",
    ),
    _spec(
        "H2_val",
        "data/v1_0/dataset_v1_0_phase_i_h2_commitment_patch_val.jsonl",
        "H2",
        "primary",
        description="Frozen H2 validation JSONL",
    ),
    _spec(
        "H2_summary",
        "data/v1_0/dataset_v1_0_phase_i_h2_commitment_patch_summary.json",
        "H2",
        "corroborating",
        description="Published H2 summary JSON",
    ),
    _spec(
        "H2_config",
        "configs/lora/stage_b_llama31_8b_base_v1_phase_i_h2_commitment_patch.config.json",
        "H2",
        "primary",
        description="Frozen H2 config",
    ),
    _spec(
        "H2_manifest",
        "manifests/runs/stage_b_llama31_8b_base_v1_phase_i_h2_commitment_patch.run_manifest.json",
        "H2",
        "primary",
        description="Frozen H2 run manifest",
    ),
    _spec(
        "H2_eval_summary",
        "evals/runs/stage_b_v1_phase_i_h2_commitment_patch_eval_20260611T120228Z/summary.json",
        "H2",
        "corroborating",
        description="Executed H2 eval summary",
    ),
    _spec(
        "H2_eval_rows",
        "evals/runs/stage_b_v1_phase_i_h2_commitment_patch_eval_20260611T120228Z/comparison_rows.jsonl",
        "H2",
        "corroborating",
        description="Executed H2 eval comparison rows",
    ),
    _spec(
        "H2_bundle_manifest",
        "evals/baselines/llama31/internal_reference_regimes/h2_commitment_patch_20260611T120228Z/package_manifest.json",
        "H2",
        "corroborating",
        description="Published H2 bundle manifest",
    ),
    _spec(
        "H2_bundle_summary",
        "evals/baselines/llama31/internal_reference_regimes/h2_commitment_patch_20260611T120228Z/summary.json",
        "H2",
        "corroborating",
        description="Published H2 bundle summary",
    ),
    _spec(
        "H2_bundle_rows",
        "evals/baselines/llama31/internal_reference_regimes/h2_commitment_patch_20260611T120228Z/comparison_rows.jsonl",
        "H2",
        "corroborating",
        description="Published H2 bundle comparison rows",
    ),
    _spec(
        "dataset_summary",
        "data/v1_0/dataset_v1_0_summary.json",
        "eval_contract",
        "corroborating",
        description="Dataset family summary",
    ),
    _spec(
        "eval_manifest",
        "evals/canonical_eval_manifest_v1.json",
        "eval_contract",
        "primary",
        description="Canonical eval manifest",
    ),
    _spec(
        "heldout_validation",
        "evals/data/canonical_v1/heldout_validation.jsonl",
        "eval_contract",
        "primary",
        description="Canonical heldout_validation split",
    ),
    _spec(
        "tool_holdout",
        "evals/data/canonical_v1/tool_holdout.jsonl",
        "eval_contract",
        "primary",
        description="Canonical tool_holdout split",
    ),
    _spec(
        "no_call",
        "evals/data/canonical_v1/no_call.jsonl",
        "eval_contract",
        "primary",
        description="Canonical no_call split",
    ),
    _spec(
        "adversarial",
        "evals/data/canonical_v1/adversarial.jsonl",
        "eval_contract",
        "primary",
        description="Canonical adversarial split",
    ),
    _spec(
        "direct_answer",
        "evals/data/canonical_v1/direct_answer.jsonl",
        "eval_contract",
        "primary",
        description="Canonical direct_answer split",
    ),
    _spec(
        "eval_scorer",
        "scripts/eval_canonical_manifest.py",
        "eval_contract",
        "primary",
        provenance_tracked=True,
        description="Canonical scorer script",
    ),
    _spec(
        "training_script",
        "scripts/train_lora_sft.py",
        "eval_contract",
        "primary",
        provenance_tracked=True,
        description="Canonical training script",
    ),
    _spec(
        "dataset_builder",
        "scripts/build_dataset_v1.py",
        "eval_contract",
        "primary",
        provenance_tracked=True,
        description="Canonical dataset builder script",
    ),
    _spec(
        "metric_spec",
        "docs/metric_specification_v1a.md",
        "eval_contract",
        "primary",
        description="Canonical metric specification",
    ),
    _spec(
        "microprobe_config",
        "configs/lora/stage_b_llama31_8b_base_v1_i10r_microprobe.config.json",
        "eval_contract",
        "corroborating",
        description="Microprobe config referenced by the canonical manifest",
    ),
    _spec(
        "env_snapshot",
        "manifests/environment/canonical_env_snapshot_v1.json",
        "environment",
        "primary",
        description="Canonical environment snapshot",
    ),
    _spec(
        "dependency_lock",
        "manifests/environment/pip_freeze_llama_venv_20260526.txt",
        "environment",
        "primary",
        description="Canonical dependency lock",
    ),
)


HASH_CLAIMS: tuple[HashClaim, ...] = (
    _claim(
        "i3_train_sha256",
        "i3_train",
        "c19dbab14d930c39b90f85de8f7bf820f1ac37035756a9ca5063f823369e3f9a",
        "data/v1_0/dataset_v1_0_stage_b_recovery_i3_summary.json",
        corroborators=(
            "manifests/runs/stage_b_llama31_8b_base_v1_i3.run_manifest.json",
            "docs/phase_i/CONTROL_SURFACE_VERIFICATION.md",
        ),
    ),
    _claim(
        "i3_val_sha256",
        "i3_val",
        "d1bde5c675e22a88df250ac91e13522bb4d9ff8685d86e3b885f6d8d106d661f",
        "data/v1_0/dataset_v1_0_stage_b_recovery_i3_summary.json",
        corroborators=(
            "manifests/runs/stage_b_llama31_8b_base_v1_i3.run_manifest.json",
            "docs/phase_i/CONTROL_SURFACE_VERIFICATION.md",
        ),
    ),
    _claim(
        "shared_control_val_sha256",
        "i3_val",
        "d1bde5c675e22a88df250ac91e13522bb4d9ff8685d86e3b885f6d8d106d661f",
        "docs/continuity/D0_HASH_AUTHORITY_VERIFICATION.md",
        corroborators=(
            "data/v1_0/dataset_v1_0_stage_b_recovery_i3_summary.json",
            "manifests/runs/stage_b_llama31_8b_base_v1_i3.run_manifest.json",
        ),
    ),
    _claim(
        "H1_train_sha256",
        "H1_train",
        "fb488f828b9ff42f2c067031ae4e7d65edecd791420c2d6daf79e27422e4e947",
        "data/v1_0/dataset_v1_0_phase_i_h1_diversity_patch_summary.json",
        corroborators=(
            "manifests/runs/stage_b_llama31_8b_base_v1_phase_i_h1_diversity_patch.run_manifest.json",
            "evals/baselines/llama31/internal_reference_regimes/h1_diversity_patch_20260611T125835Z/package_manifest.json",
            "docs/phase_i/DATASET_VARIANT_VALIDATION.md",
        ),
    ),
    _claim(
        "shared_control_val_sha256",
        "H1_val",
        "d1bde5c675e22a88df250ac91e13522bb4d9ff8685d86e3b885f6d8d106d661f",
        "data/v1_0/dataset_v1_0_phase_i_h1_diversity_patch_summary.json",
        corroborators=(
            "docs/continuity/D0_HASH_AUTHORITY_VERIFICATION.md",
            "docs/phase_i/DATASET_VARIANT_VALIDATION.md",
        ),
    ),
    _claim(
        "H2_train_sha256",
        "H2_train",
        "41834b7dd1b06bf90bfdb38b77c15f67a3dfdab802d164b0edddfcc686a75fd5",
        "data/v1_0/dataset_v1_0_phase_i_h2_commitment_patch_summary.json",
        corroborators=(
            "manifests/runs/stage_b_llama31_8b_base_v1_phase_i_h2_commitment_patch.run_manifest.json",
            "evals/baselines/llama31/internal_reference_regimes/h2_commitment_patch_20260611T120228Z/package_manifest.json",
            "docs/phase_i/DATASET_VARIANT_VALIDATION.md",
        ),
    ),
    _claim(
        "shared_control_val_sha256",
        "H2_val",
        "d1bde5c675e22a88df250ac91e13522bb4d9ff8685d86e3b885f6d8d106d661f",
        "data/v1_0/dataset_v1_0_phase_i_h2_commitment_patch_summary.json",
        corroborators=(
            "docs/continuity/D0_HASH_AUTHORITY_VERIFICATION.md",
            "docs/phase_i/DATASET_VARIANT_VALIDATION.md",
        ),
    ),
    _claim(
        "canonical_eval_manifest_sha256",
        "eval_manifest",
        "a5035f41e89764519df3079d8786392b8c6d21dd2da487d00748dd595ec3d9a0",
        "docs/phase_i/CONTROL_SURFACE_VERIFICATION.md",
        corroborators=(
            "evals/canonical_eval_manifest_v1.json",
            "docs/phase_i/EXECUTION_GATE_APPROVAL.md",
        ),
    ),
    _claim(
        "dataset_manifest_sha256",
        "dataset_summary",
        "86f68710d7257bb43793fb6a47245a232a3d390e55890604e8926676e6a2b4fd",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=(
            "data/v1_0/dataset_v1_0_summary.json",
            "manifests/reports/stage_c_package2a_read_file_exact_valid_gate_evidence_run_a.json",
        ),
    ),
    _claim(
        "scorer_sha256",
        "eval_scorer",
        "08a5cec22a781193365bed85b709ceebef534846602004bbfa047f4e0b59d738",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=(
            "docs/phase_i/CONTROL_SURFACE_VERIFICATION.md",
            "docs/phase_e_remediation/REMEDIATION_RECOMMENDATION.md",
        ),
    ),
    _claim(
        "training_script_sha256",
        "training_script",
        "28900accae3d6abf05ddb9e86b41c03ad3c812a683f3af343bffa94281e14c8b",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=("docs/phase_i/CONTROL_SURFACE_VERIFICATION.md",),
    ),
    _claim(
        "dataset_builder_sha256",
        "dataset_builder",
        "05843673f68fc8a492e889fb9e96e87dff09d189f5df220b092f233de82839d9",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=("docs/phase_i/CONTROL_SURFACE_VERIFICATION.md",),
    ),
    _claim(
        "metric_spec_sha256",
        "metric_spec",
        "793a884bbd783c3559828ab2cf84e4ceccc2aab256a80cf360c624dd8a549a3d",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=("docs/phase_i/CONTROL_SURFACE_VERIFICATION.md",),
    ),
    _claim(
        "microprobe_config_sha256",
        "microprobe_config",
        "d84ccad264787f1660c0709e4078c616b16ea4edda155f71269395c5f1859806",
        "docs/phase_i/CONTROL_SURFACE_VERIFICATION.md",
        corroborators=("manifests/reports/stage_b_v1_i10r_microprobe_reproducibility_snapshot.json",),
    ),
    _claim(
        "heldout_validation_sha256",
        "heldout_validation",
        "78d47d4fb974f0f3245eaf81a17a847febc2667da5926bd372f625cd00b127a5",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=(
            "evals/runs/stage_b_v1_phase_i_h0_control_i3_micro_eval_20260611T103048Z/summary.json",
            "evals/baselines/llama31/canonical_baselines/base_original_20260526T0044Z/summary.json",
        ),
    ),
    _claim(
        "tool_holdout_sha256",
        "tool_holdout",
        "ca492290645cdf3e374bdd456b9488500c594b080180caae9b3b73fe288d0f45",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=(
            "evals/runs/stage_b_v1_phase_i_h0_control_i3_micro_eval_20260611T103048Z/summary.json",
            "evals/baselines/llama31/canonical_baselines/base_original_20260526T0044Z/summary.json",
        ),
    ),
    _claim(
        "no_call_sha256",
        "no_call",
        "0584f529d86b8b319b2abaaa2410e504d614243f32a56a3a1eae44e8f8768fa7",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=(
            "evals/runs/stage_b_v1_phase_i_h0_control_i3_micro_eval_20260611T103048Z/summary.json",
            "manifests/reports/stage_c_package2a_read_file_exact_valid_gate_evidence_run_a.json",
        ),
    ),
    _claim(
        "adversarial_sha256",
        "adversarial",
        "c500b8195722355b54dc7ddb612690daa9ef530ba4b030bcd04c7c2b2b50c5cc",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=(
            "evals/runs/stage_b_v1_phase_i_h0_control_i3_micro_eval_20260611T103048Z/summary.json",
            "manifests/reports/stage_c_package2a_read_file_exact_valid_gate_evidence_run_a.json",
        ),
    ),
    _claim(
        "direct_answer_sha256",
        "direct_answer",
        "969d1d5dde3b17515c45c9a5f4b69beb1d908063f61ce470f778d625b1b1afbd",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=(
            "evals/runs/stage_b_v1_phase_i_h0_control_i3_micro_eval_20260611T103048Z/summary.json",
            "manifests/reports/stage_c_package2a_read_file_exact_valid_gate_evidence_run_a.json",
        ),
    ),
    _claim(
        "environment_snapshot_sha256",
        "env_snapshot",
        "ae3f853694c2f940bf015772d4e639004f49eb4646f54395ad8a536d05f187d3",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=("manifests/reports/stage_b_v1_i10r_microprobe_reproducibility_snapshot.json",),
    ),
    _claim(
        "dependency_lock_sha256",
        "dependency_lock",
        "e75c5cc0673060e154baf99ff12a85a6ad8d10bee3e2d54181f859c861493cf5",
        "evals/canonical_eval_manifest_v1.json",
        corroborators=("manifests/reports/stage_b_v1_i10r_microprobe_reproducibility_snapshot.json",),
    ),
)


AUTHORITY_SURFACES: tuple[AuthoritySurface, ...] = (
    _surface(
        "i3",
        "i3 scaffold",
        ("i3_train", "i3_val", "i3_summary", "i3_config", "i3_manifest"),
        corroborating_artifact_ids=(),
        notes=("Control scaffold surface; H0 reuses the control val bytes.",),
    ),
    _surface(
        "H0",
        "H0 control comparator",
        ("H0_config", "H0_manifest", "i3_train", "i3_val"),
        corroborating_artifact_ids=("H0_eval_summary", "H0_eval_rows", "i3_summary", "i3_manifest"),
        notes=("Metadata-only control comparator built against i3 control bytes.",),
    ),
    _surface(
        "H1",
        "H1 diversity patch",
        ("H1_train", "H1_val", "H1_config", "H1_manifest"),
        corroborating_artifact_ids=(
            "H1_summary",
            "H1_eval_summary",
            "H1_eval_rows",
            "H1_bundle_manifest",
            "H1_bundle_summary",
            "H1_bundle_rows",
        ),
        notes=("Replacement patch surface with 100-row patch accounting.",),
    ),
    _surface(
        "H2",
        "H2 commitment patch",
        ("H2_train", "H2_val", "H2_config", "H2_manifest"),
        corroborating_artifact_ids=(
            "H2_summary",
            "H2_eval_summary",
            "H2_eval_rows",
            "H2_bundle_manifest",
            "H2_bundle_summary",
            "H2_bundle_rows",
        ),
        notes=("Replacement patch surface with 100-row patch accounting.",),
    ),
    _surface(
        "eval_contract",
        "canonical eval contract",
        (
            "dataset_summary",
            "eval_manifest",
            "heldout_validation",
            "tool_holdout",
            "no_call",
            "adversarial",
            "direct_answer",
            "eval_scorer",
            "training_script",
            "dataset_builder",
            "metric_spec",
            "microprobe_config",
        ),
        corroborating_artifact_ids=(),
        notes=("Frozen eval contract and its supporting code/docs.",),
    ),
    _surface(
        "environment",
        "environment snapshot",
        ("env_snapshot", "dependency_lock"),
        notes=("Frozen environment comparability surface.",),
    ),
)


AUTHORITY_INPUTS: tuple[str, ...] = (
    "docs/continuity/D0_RECONSTRUCTION_AUTHORITY_MATRIX.md",
    "docs/continuity/D0_RECONSTRUCTION_IMPLEMENTATION_PLAN.md",
    "docs/continuity/D0_VALIDATION_CHECKLIST.md",
    "docs/continuity/D0_ACCEPTANCE_CRITERIA.md",
    "docs/continuity/D0_HASH_AUTHORITY_VERIFICATION.md",
    "docs/continuity/D0_EXECUTION_SEQUENCE.md",
)
